### ISSUE TITLE
Side Mission Vehicle Removal does not work

### ISSUE THREAD

**Issue by christian2526** [TaskForce47/Domination-Lingor#2]
Side Mission Fahrzeuge die geklaut worden sind despawnen nicht.

**Comment by 4Lucke** [comment]
ich glaube der fehler besteht darin das die variable _vec ist und nicht _veh

**Comment by christian2526** [comment]
Bitte testen.

**Comment by phumberdroz** [comment]
crew dismount hatte wohl mal nicht funktioniert.

**Comment by phumberdroz** [comment]
Crew Dismount funktioniert wohl aber die höhe ist wohl egal. 

Sollten wir auf 1 Meter höher in der reached base stellen.

**Comment by christian2526** [comment]
Siehe #27

**Comment by phumberdroz** [comment]
@christian2526 kannst du es dir mal angucken bei Gelegenheit.
