### ISSUE TITLE
UAC

### ISSUE THREAD

**Issue by phumberdroz** [TaskForce47/Domination-Lingor#21]
UAC am Null-Punkt spawnen ?

Aktuell spawnen sie in der Nähe der Main anscheinend aber nicht sicher ob dann erst der marker auftaucht.

@christian2526

**Comment by 4Lucke** [comment]
Meine Beobachtung dazu:

1. Fahrzeuge werden am Null-Punkt gespawnt.
2. UAC Marker ist schon dort sichtbar.
3. Fahrzeuge werden um die Main rum verteilt (geportet). 

Vorschläge:

- UAC werden nicht direkt um die Main gespawnt sonder in eine größren Radius darum (5-10 km vielleicht?)
- Meldungen das ein UAC gespottet wurden, sodass man nichtmehr überrascht wird.

**Comment by phumberdroz** [comment]
Meldung empfinde ich für zu "krass" / einfach. 

Wenn die UACs an einen Der karten ränder spawnen sollte das meiner Meinung nach Ausreichen. Also Eck Punkte. Macht es den Spielern erstmal einfach das ganze einzuschätzen.

**Comment by phumberdroz** [comment]
UACs spawnen am Map rand war wohl einfach pech.
