### ISSUE TITLE
Destroy Objectives Sprengmittel

### ISSUE THREAD

**Issue by phumberdroz** [TaskForce47/Domination-Lingor#24]
Hey,

was haltet ihr davon wenn wir es erlauben Destroy Objectives durch ATs zu zerstören.

**Comment by christian2526** [comment]
Nicht so viel, die Leute sollen die Teile sprengen, sonst kommt ein Harry mit der Javelin und macht die Mission bevor ein Team da ist und stört damit, meiner Meinung nach, den Spielfluss der Mehrheit.
