### ISSUE TITLE
Abort und tickets

### ISSUE THREAD

**Issue by 4Lucke** [TaskForce47/Domination-Lingor#25]
Da das ganze bei der Liberation schon umgesetzt wurde und ich das ganze auch nicht schlecht fand.
Wenn jemand bewusstloss ist und dann zurück in die lobby geht oder den Server verlässt werden dennoch die Tickets für deren "tot" abgezogen.

**Comment by christian2526** [comment]
@mindbl4ster hast du hierfür den benötigten Code`?

**Comment by mindbl4ster** [comment]
addMissionEventHandler ["HandleDisconnect",{     if ( (_this select 0) getVariable ["ace_isunconscious", false] )then{[TF47_helper_playerFaction,-1] call BIS_fnc_respawnTickets};    }]; 
muss halt angepasst werden an die corescipt tickets

**Comment by phumberdroz** [comment]
https://github.com/TaskForce47/Domination-Lingor/blob/master/tf47CoreScripts/serverEvents.sqf#L31-L58

da muss das hin jemand lust nen pull request zu machen ?

**Comment by 4Lucke** [comment]
in ef1c1aa738ec30cac0322f67455a92bb19df9b17 hinzugefügt. muss noch getestet werden.

**Comment by 4Lucke** [comment]
added in #55
