### ISSUE TITLE
Schwebende Flaggen auf den Bunkern

### ISSUE THREAD

**Issue by 4Lucke** [TaskForce47/Domination-Lingor#26]
![107410_20170120200428_1](https://cloud.githubusercontent.com/assets/13781873/22166612/37c86cc8-df62-11e6-902f-2a05a1d9c62a.png)
Tritt soweit ich weiß bei allen Bunkern auf.

**Comment by phumberdroz** [comment]
Du meinst die Flagge?

**Comment by phumberdroz** [comment]
Ist geändert. 

Sieht jetzt so aus: 
![](http://images.akamai.steamusercontent.com/ugc/101729909456020907/B79286973454A17227D64FD4D670D1C4D18C0E91/)
