### ISSUE TITLE
Sidemission Power plant (fueltanks) zerstören verbuggt.

### ISSUE THREAD

**Issue by 4Lucke** [TaskForce47/Domination-Lingor#27]
http://www.antihelios.de/EK/Arma/images/Land_dp_bigTank_F.jpg
Mission File: x_missions\ma3a\x_m45.sqf
Diese Objekte gibt es auf Linogr nicht.  Definiert in der x_init\fn_preinit.sqf Zeile 648. 
`_sm_land_tankbig = "Land_dp_bigTank_F";`
Allgemein finde ich es gefährlich nach bestimmten Objekten zu suchen in der "hoffnung" das spieler diese erkennen und zerstören.

**Comment by christian2526** [comment]
Wontfix, diese Typ Sidemissions (Factory) werden nach und nach durch andere Arten von Sides ausgetauscht, Side 45 und 46 sind jetzt "Destroy Anti Air Radar" Missionen.

Damit Resolved.
