### ISSUE TITLE
Script Fehler in initPlayerLocal.sqf

### ISSUE THREAD

**Issue by TheNiner** [TaskForce47/Domination-Lingor#28]
![missingaddons](https://cloud.githubusercontent.com/assets/4367282/22175390/19906fe8-dff4-11e6-9080-0e25e049715e.JPG)

**Comment by phumberdroz** [comment]
haste deine addons nicht mitgestartet ? 

Wird gefixxt.

**Comment by TheNiner** [comment]
A3S hatte eine falsche Addon Group gestartet.
