### ISSUE TITLE
Name anzeige bei Whitelist Fahrzeugen (marker oben rechts) funktionieren nicht nach Vehicle Respawn

### ISSUE THREAD

**Issue by christian2526** [TaskForce47/Domination-Lingor#31]
getesten/aufgefallen bei Raven 01

**Comment by phumberdroz** [comment]
nicht 100% sicher aber könnte evtl. wieder funktionieren.

**Comment by 4Lucke** [comment]
ich glaube beim respawnen werden die globalen variablen nicht erneuert
