### ISSUE TITLE
Zurückeroberte Städte sollten Tickets geben

### ISSUE THREAD

**Issue by phumberdroz** [TaskForce47/Domination-Lingor#33]
Hey, 

zurückeroberte Städte die vom Feind wieder geholt worden und dann wiederum von uns wieder geholt werden sollten tickets geben 5 ? :)

**Comment by christian2526** [comment]
Probeweise drin, testen wenn möglich

**Comment by phumberdroz** [comment]
Ist counter attack nicht ein event während einer Main mission?
