### ISSUE TITLE
hmmwvs können nicht respawnt werden?

### ISSUE THREAD

**Issue by mindbl4ster** [TaskForce47/Domination-Lingor#35]
respawn der hmmwvs scheint nach längerer zeit nicht mehr lauffähig zu sein. gestern das problem gehabt dass das service menu für die hmmwvs nicht mehr ging und bereits für respawn getaggte fahrzeuge nicht verschwunden sind aber bereits vom system blockiert wurden.

**Comment by mindbl4ster** [comment]
evtl service menu eventbasiert über aceinteraction?

**Comment by phumberdroz** [comment]
ja kommt mit dem Corescript rewrite. 

Das problem ist allerdings simple zu fixen ich habs nur vergessen die variable wird nicht zurück gesetzt für das fahrzeug glaube ich.. Ich check nochmal

**Comment by christian2526** [comment]
Das ist das allgemeine Problem mit den Fahrzeuge die respawnt wurden.

**Comment by phumberdroz** [comment]
48d9030  fixed that.
