### ISSUE TITLE
Basedefense

### ISSUE THREAD

**Issue by mindbl4ster** [TaskForce47/Domination-Lingor#38]
grund: basedefense schluckt unmengen an performance für ai und fahrzeuge im rendering und erfüllt ihren zweck nur mäßig bis gar nicht.
vorschlag meinerseits wären 2 a10c um die base loitern lassen und alles was näher als ein 1km an die base kommt mit _x setDamage 1 zerstören. arbeitet zuverlässiger und sieht evtl schöner aus ;)
tanks kann man ja rein zur zierde noch als simpleobjects rumstehen lassen.

**Comment by christian2526** [comment]
Finde ich gut! Mehr Feedback erwünscht

**Comment by christian2526** [comment]
Wie wäre es, wenn man das direkt (sollte es für gut befunden werden) in die Cores mit einbaut?

**Comment by christian2526** [comment]
Base Defense:

1000m Base -> Destroy
600m Base -> setDamage 1
