### ISSUE TITLE
u menu

### ISSUE THREAD

**Issue by mindbl4ster** [TaskForce47/Domination-Lingor#40]
es wurde der wunsch geäußert das alte u menu wieder einzubaun und den chat bis auf den direct chat vollständig zu disablen.

any coments?

**Comment by phumberdroz** [comment]
was kann das u menu? Was tut es ?

**Comment by mindbl4ster** [comment]
das ist die gui mit dem sich teams auf der karte mit einheiten typ und tfar frequenz eintragen konnten.  das umgeht die notwendigkeit den side oder global channel freizuschalten um marker zu erstellen die für alle ersichtlich sind.

**Comment by phumberdroz** [comment]
Kann man dafür evtl auch das standard BIS Group dings benutzen ?

**Comment by mindbl4ster** [comment]
wie besprochen kommt was eigenes die tage.
