### ISSUE TITLE
Kisten Spawner

### ISSUE THREAD

**Issue by christian2526** [TaskForce47/Domination-Lingor#50]
Kisten Spawner

https://forum.armasim.de/forum/index.php/Thread/4776-Eigener-Kisten-Spawnpunkt/

**Comment by TheNiner** [comment]
Wenn euch einfache Actions reichen, könnte ich den Kisten Spawner aus IAA/Sup einbauen

**Comment by phumberdroz** [comment]
mit loadouts ? :)

**Comment by christian2526** [comment]
@TheNiner jap, reicht vollkommen aus.
@Meat Aber die Leute sollen doch wenigstens etwas packen

**Comment by phumberdroz** [comment]
Ach ich will nur nicht das sie ewig und 2 jahre in der basis stehen.
