### ISSUE TITLE
server netzwerk performance leidet zeitweise massiv

### ISSUE THREAD

**Issue by mindbl4ster** [TaskForce47/Domination-Lingor#51]
server wird durch unbekannte ursache bei netzwerktraffic massiv eingeschränkt. lag führt zu disconnects von >80% der spieler aufgrund von zeitüberschreitung

**Comment by phumberdroz** [comment]
naja wenn man das repo über den game server root laufen lässt kein wunder.

**Comment by mindbl4ster** [comment]
zu dem zeitpunkt war aber keine offene verbindung zum repo.

**Comment by phumberdroz** [comment]
tja aber ohne mehr infos kann ich daran auch nicht arbeiten.
