### ISSUE TITLE
challenge fehlt

### ISSUE THREAD

**Issue by mindbl4ster** [TaskForce47/Domination-Lingor#54]
mittlerweile laufen die leute blind durch die ao ... solln wir die daumenschrauben anziehen?

**Comment by phumberdroz** [comment]
vielleicht helfen ja cup fahrzeuge? 👍 

Naja was hast du den für ideen?

**Comment by mindbl4ster** [comment]
medical system verschärfen? ki skill hochsetzen? vcom giftiger einstellen? alle tanks in der ai großräumig patrouillieren lassen?
